# 应用信息
app:
    name: 体适能
    description: Open and comprehensive practice management platform for students in Beijing.
    version: 1.0.0

server:
    context-path: /physicalFitness
    port: 8080
    session-timeout: 3600

timer:
    #  rate: 500000000
    #  delay: 500000000
    # 每天10点开始对账
    cron: "0 0 10 * * ?"
    # 间隔一个半小时刷新调用凭证
    cron1: "0 */30 */1 * * ?"
    # 推送提醒
    cron2: "0 0 */1 * * ?"
    test: "5,15,25 * * * * *"
    autoreceive: "0 30 5 * * *"
    weekexporturl: "http://${HOST:127.0.0.1}:${PORT:8080}/api/servicemanager/build_week_excel" #上线时需要将此地址的端口改为正式服务器的端口

timer1:
    #  rate: 500000000
    #  delay: 500000000
    #  cron: "*/5 5 * * * *"
    test: "5,15,25 * * * * *"
    autoreceive: "0 20 17 * * *"

# 日志配置
logging:
    file: ${LOG_FILE:filelogs/physicalFitness.log}
    level:
        ROOT: ${LOG_LEVEL:ERROR}
        com.ichzh: ${LOG_LEVEL:INFO}
        com.ichzh.physicalFitness.bean: ${LOG_LEVEL:INFO}
        com.ichzh.physicalFitness.web.filter: ${LOG_LEVEL:WARN}
        org.springframework.security: ${LOG_LEVEL:ERROR}

spring:
    jackson:
        # 时区
        time-zone: GMT+8
    datasource: # 数据源配置
        first:
            url: jdbc:mysql://${DB_HOST:58.132.166.240}:${DB_PORT:3306}/easy4enrol?useUnicode=true&characterEncoding=utf8
            #url: jdbc:p6spy:mysql://localhost:3306/project_tpl?useUnicode=true&characterEncoding=utf8
            username: ${DB_USER:yjf}
            password: ${DB_PASSWORD:yangjinfei}
            driverClassName: com.mysql.jdbc.Driver
            #driverClassName: com.p6spy.engine.spy.P6SpyDriver
            testOnBorrow: true
            testWhileIdle: true
            validationQuery: SELECT 1
            maxActive: 100
            minIdle: 1
    thymeleaf:
        cache: false
    redis:
        database: 0 #数据库名
        host: ${REDIS_HOST:58.132.166.239} #服务器地址
        password: ${REDIS_PASSWORD:Admin@chzh.cn2018}
        port: ${REDIS_PORT:6379}
        pool:
            max-idle: 10
            min-idle: 8
            max-active: 10000
            max-wait: 2000
            testOnBorrow: true
            testOnReturn: true
            testWhileIdle: true
        sentinel:
            master:
            nodes: ${REDIS_HOST:58.132.166.239}:${REDIS_PORT:26380},${REDIS_HOST:58.132.166.239}:${REDIS_PORT:26381},${REDIS_HOST:58.132.166.239}:${REDIS_PORT:26382}
        timeout: 2000 #毫秒
    jpa:
        show-sql: false
        properties:
            javax:
                persistence:
                    validation:
                        mode: none
    # 解决由MySQL版本导致的问题
    #database-platform: org.hibernate.dialect.MySQLDialect
    profiles:
      # 导入其他配置文件
      active: minio
    http:
        # 上传文件大小限制，默认1Mb，－1表示不限制，Action中使用@RequestParam("file") MultipartFile file
        multipart:
            maxFileSize: 20Mb
            maxRequestSize: 22Mb
#  mvc:
#     static-path-pattern: '/test/**'
# 登录配置文件
loginConfig:
    lockTime: 1  #登录错误次数达到上线后，账号锁定的时间，单位：分钟
    loginFailNum: 10  #允许连续登录失败的错误次数
    # 是否开启验证码功能
    captcha: true
    # sql语句写在yml文件中，指定具体使用的文件（多个文件用半角逗号隔开）
    sqlYmls: sqls.yml,sqls_lyr.yml,sqls_yjf.yml,sqls_pzx.yml,sqls_ssn.yml
    # 允许跨域的域名（多个使用半角逗号分隔，每个域名都要指名http或https,最后不能有“/”）
    allowDomains: https://hm.baidu.com,http://webchat.7moor.com
    allowMethods: GET,POST,OPTIONS
    # 认证登录过期时间（分钟）
    expirationMinutes: 360
#应用中的常亮配置放在此处
selfConfig:
    #是否启动定时任务 0 不启动 1 启动
    ifStartScheduledTask: ${ifStartScheduledTask:1}
    # 当前节点所在机器字典码
    machineId: ${MACHINEID:SX01}
    # 是否使用沙箱仿真测试系统
    sandboxnew: false
    # 获取沙箱仿真验签秘钥API
    signkeyUrl: https://api.mch.weixin.qq.com/sandboxnew/pay/getsignkey
    # 小程序 appId
    appid: wx519fef2ffaa3b3b1
    # 小程序 appSecret
    secret: 39f76369767d512149291e4b26919829
    # 小程序 商户平台设置的密钥key(key设置路径：微信商户平台(pay.weixin.qq.com)-->账户设置-->API安全-->密钥设置)
    key: 39f76369767d512149291e4b26919829
    # 小程序 授权类型
    grantType: authorization_code
    # 小程序 微信支付分配的商户号
    mchId: 1582254771
    # 小程序 自定义参数，可以为终端设备号(门店号或收银设备ID)，PC网页或公众号内支付可以传"WEB"
    deviceInfo: WEB
    # 小程序 签名类型，默认为MD5，支持HMAC-SHA256和MD5。
    signType: MD5
    # 小程序 交易类型
    tradeType: JSAPI
    # 小程序 登录凭证校验 api
    code2SessionUrl: https://api.weixin.qq.com/sns/jscode2session
    # 获取小程序全局唯一后台接口调用凭据 api
    tokenUrl: https://api.weixin.qq.com/cgi-bin/token
    # 小程序 统一下单 api
    unifiedorderUrl: https://api.mch.weixin.qq.com/pay/unifiedorder
    # 小程序 下载交易账定
    downloadbillUrl: https://api.mch.weixin.qq.com/pay/downloadbill
    # 小程序 查询订单
    orderqueryUrl: https://api.mch.weixin.qq.com/pay/orderquery
    # 小程序 关闭订单
    closeorderUrl: https://api.mch.weixin.qq.com/pay/closeorder
    # 微信支付结果通知回调 uri
    notifyUrl: /callBack/wxPayNotify

    # 微信申请消息服务器填写的的token
    token: 949a258e39844bf7aace5140e9f8286d
    # 微信申请消息服务器填写的消息加密密钥
    encodingAESKey: jjP6mipz9PhRtvYJKt1msZVxCx2AeU1OmqNTYy2ROx0
    # 微信申请消息服务器时选择的加密方式（1:明文模式、2:兼容模式、3:安全模式）；当前进支持模式2
    encryMode: 2
    # 微信申请消息服务器时选择的数据格式；当前进支持json
    dataType: json
    # 发送客服消息给用户 api 公众号发送客服消息api
    customerServiceMessageSendUrl: https://api.weixin.qq.com/cgi-bin/message/custom/send
    # 添加客服帐号
    customserviceKfaccountAddUrl: https://api.weixin.qq.com/customservice/kfaccount/add
    # 客服信息响应文本
    resCustomer: 
        "好入学":  "好入学社区\n\n<a href='https://%s%s/wechatclientservice/qrcode.html'>点击跳二维码页面</a>"
        "幼升小":  "好入学-幼升小社区\n\n<a href='https://%s%s/wechatclientservice/qrcode_ysx.html'>点击跳二维码页面</a>"
        "小升初":  "好入学-小升初社区\n\n<a href='https://%s%s/wechatclientservice/qrcode_xsc.html'>点击跳二维码页面</a>"

    #公众号APPID
    publicAppId: wx33a2bec40c2367c4
    #公众号 appSecret
    publicAppSecret: 5615d233dc13b64f116892471fd7c29c
    # 小程序发送订阅消息
    subscribeMessageSendUrl: https://api.weixin.qq.com/cgi-bin/message/subscribe/send
    # 小程序模板数据配置
    subscribeMessageMap:
        test:
            # 所需下发的订阅模板id
            template_id: VSH6iCKjz9i7vNwpV4CzAXEas8rkRAgOKmvg4PyEup8
            # 点击模板卡片后的跳转页面，仅限本小程序内的页面。支持带参数,（示例index?foo=bar）。该字段不填则模板无跳转。
            page: pages/home/index
            # 模板内容，格式形如 { "key1": { "value": any }, "key2": { "value": any } }
            # 详情查看 https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html 的订阅消息参数值内容限制说明
            data:
                # 活动名称
                thing1:
                    value: 好入学入学政策
                # 活动时间
                time2:
                    value: 2020-05-10
                # 温馨提醒
                thing3:
                    value: 注意出行安全
                # 通知时间
                date4:
                    value: 2020-05-09
        scheduleReminder:
            # 所需下发的订阅模板id
            template_id: VSH6iCKjz9i7vNwpV4CzAXEas8rkRAgOKmvg4PyEup8
            # 点击模板卡片后的跳转页面，仅限本小程序内的页面。支持带参数,（示例index?foo=bar）。该字段不填则模板无跳转。
            page: pages/home/index
            # 模板内容，格式形如 { "key1": { "value": any }, "key2": { "value": any } }
            # 详情查看 https://developers.weixin.qq.com/miniprogram/dev/api-backend/open-api/subscribe-message/subscribeMessage.send.html 的订阅消息参数值内容限制说明
            data:
                # 活动名称
                thing1:
                    value: 好入学入学政策
                # 活动时间
                time2:
                    value: 2020-05-10
                # 温馨提醒
                thing3:
                    value: 注意出行安全
                # 通知时间
                date4:
                    value: 2020-05-09                    
            # 跳转小程序类型：developer为开发版；trial为体验版；formal为正式版；默认为正式版
            miniprogram_state: developer
            # 进入小程序查看”的语言类型，支持zh_CN(简体中文)、en_US(英文)、zh_HK(繁体中文)、zh_TW(繁体中文)，默认为zh_CN
            lang: zh_CN
    # 公众号发送订阅消息
    templateMessageSendUrl: https://api.weixin.qq.com/cgi-bin/message/template/send
    # 公众号模板数据配置
    templateMessageMap:
        test:
            # 模板id
            template_id: YT3EQ3Tm7EFV75q02fAkPEIjM4b-mLGBIsthEkcDTX8
            # 模板跳转链接（海外帐号没有跳转能力）
            url: ''
            # 跳小程序所需数据，不需跳小程序可不用传该数据
            miniProgram:
                # 所需跳转到的小程序appid（该小程序appid必须与发模板消息的公众号是绑定关联关系，暂不支持小游戏）
                appid: ${selfConfig.appid}
                # 所需跳转到小程序的具体页面路径，支持带参数,（示例index?foo=bar），要求该小程序已发布，暂不支持小游戏
                pagepath: pages/home/index
            # 模板数据
            data:
                first:
                    value: 学员张小明今天上课记录变化啦
                    color: #173177
                keyword1:
                    value: 书法中级班
                    color: #173177
                keyword2:
                    value: 减 2 个课时
                    color: #173177
                keyword3:
                    value: 2015年2月1日
                    color: #173177
                keyword4:
                    value: 17:00 - 19:00
                    color: #173177
                remark:
                    value: 感谢您的支持，如有疑问，请随时同我们联系！
                    color: #173177
        scheduleReminder:
            # 模板id
            template_id: MxqB3djL5lBIx36WBkNFRAdtDyhs0kQbuUQmVpLG2zo
            # 模板跳转链接（海外帐号没有跳转能力）
            url: ''
            # 跳小程序所需数据，不需跳小程序可不用传该数据
            miniProgram:
                # 所需跳转到的小程序appid（该小程序appid必须与发模板消息的公众号是绑定关联关系，暂不支持小游戏）
                appid: ${selfConfig.appid}
                # 所需跳转到小程序的具体页面路径，支持带参数,（示例index?foo=bar），要求该小程序已发布，暂不支持小游戏
                pagepath: pages/home/index
            # 模板数据
            data:
                first:
                    value: 入学日历已订阅
                    color: #173177
                keyword1:
                    value: XX区 上小\中学 京籍（非京籍）\入学方式
                    color: #173177
                keyword2:
                    value: 2020年XX月XX日（当前提醒事项）
                    color: #173177              
                remark:
                    value: 请您持续关注好入学，我们会不断更新入学服务！
                    color: "#E6421A"                   
    # 程序小卡片配置
    appletCardMap:
        attention:
            # 小卡片标题
            title: 快速了解北京幼升小、小升初入学攻略！
            # 小程序appid
            appid: ${selfConfig.appid}
            # 小程序页面
            pagepath: pages/home/index
            # 小程序消息卡片的封面，通过 新增素材接口 上传图片文件获得，建议大小为 520*416
            thumb_media_id: Av8dtigBTqnLJRRSVfRIgUW5ZtzVXL17er2xxfqSFDQ
    # 关注公众号，客服先推送一段文本，然后发送小程序卡片，这是文本配置，使用map，可多个配置
    textMap:
        attentionContent: "感谢您关注好入学！\n我们会为您定期推送最新的入学信息，帮助您快速了解入学政策的变化。通过海量的信息处理加之专业的教育评估模型，为您提供更全面、客观、可量化的学校信息，为您的升学择校的提供有力支持！更多详情，可以点击小程序了解！"
    # 公众号查询用户信息api
    userInfoUrl: https://api.weixin.qq.com/cgi-bin/user/info
    # 短信验证码内容
    smsMessage: 您正在绑定手机号，验证码:%s
    # 短信验证码过期时间(毫秒) 10 分钟
    smsTime: 600000
    # 是否真实发送短信
    enableSms: false
    # 绑定付费api的信息类型的字典类型
    infoKindType: 110
    # 支付过期时间(分钟)
    payTime: 10
