# https 配置
https:
    port: ${PORTS:8443}
    ssl:
        # 证书路径
        key-store: classpath:keystore.p12
        key-store-type: PKCS12
        key-alias: tomcat
        # 配置密码，就是在生成证书的时候输入的密码
        key-store-password: parrot_2019
    # 证书路径（非框架读取）
    key-store-source: keystore.p12
    # 是否开启https
    enable: true