# OAuth2配置
security:
    oauth2:
        client:
            clientId: ${CLIENTID:10000001}
            clientSecret: ${CLIENTSECRET:96e79218965eb72c92a549dd5a330112}
            accessTokenUri: ${ACCESSTOKENURI:http://211.153.66.106:9004/cfcc02/oauth/Token.a}
            userAuthorizationUri: ${USERAUTHORIZATIONURI:http://211.153.66.106:9004/cfcc02/oauth/Auth.a}
            clientAuthenticationScheme: form
        resource:
            userInfoUri: ${USERINFOURI:http://211.153.66.106:9004/cfcc02/Api.a?api_name=user_get_info}